### ISSUE TITLE
SW Design Suggestions

### ISSUE THREAD

**Issue by wilkenstein** [jonluca/USC-Schedule-of-Classes-API#4]
Hi JonLuca! I'm going to use this issue to track suggestions I see on the software design front.

**Comment by wilkenstein** [comment]
https://github.com/jonluca/USC-Schedule-of-Classes-API/blob/master/utils/api.js#L27

Putting this functionality in the utils directory is somewhat non-idiomatic. There isn't a right or wrong way to structure express node.js projects, but typically, many organizations would use an app/ directory where this functionality, along with your app.js file, would go

**Comment by wilkenstein** [comment]
https://github.com/jonluca/USC-Schedule-of-Classes-API/blob/master/routes/admin.js#L6

Same comment here as above. Unifying into an app/ directory may make the repository clearer potentially.

**Comment by jonluca** [comment]
Hi Brian! Not sure if you saw my email, but this project is actually slightly deprecated. It's written quite poorly, and is being rewritten [here](https://github.com/jonluca/USC-Class-Notifier-API)

[Also, this is the project I was talking about last week](https://github.com/jonluca/Anubis)

**Comment by wilkenstein** [comment]
Oh hahah gotcha, GitHub showed this project first when I searched for you! Weird. Closing
